import type { Metadata } from "next";
import { Kaushan_Script, Poppins } from "next/font/google";

import "./globals.css";

const kaushan = Kaushan_Script({ weight:'400', subsets:['latin'], variable:'--font-kaushan' });
const poppins = Poppins({ weight:['600','500','400','300'], subsets:['latin'], variable:'--font-poppins' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${kaushan.variable}`}>
        {children}
        </body>
    </html>
  );
}
